package updater

import (
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"runtime"
	"strings"
	"time"
)

const repo = "AgusRdz/bonsai"

// maxResponseBytes caps HTTP response reads to prevent memory exhaustion
// from a compromised or spoofed endpoint.
const maxResponseBytes = 1 << 20 // 1 MiB

var httpClient = &http.Client{
	Timeout: 30 * time.Second,
}

// publicKey is the hex-encoded Ed25519 public key used to verify release signatures.
// Generated by 'make keygen' — do not edit manually.
const publicKey = "0378500538d0f613b5f7bd1c035c8129510d7c1a10274b76028f7dbeb3c840c6"

type ghRelease struct {
	TagName string `json:"tag_name"`
}

// Run checks for the latest version and updates the binary if a newer one exists.
func Run(currentVersion string) {
	if IsDev(currentVersion) {
		fmt.Println("dev build — update skipped")
		return
	}

	fmt.Println("checking for updates...")

	latest, err := latestVersion()
	if err != nil {
		fmt.Fprintf(os.Stderr, "bonsai: failed to check for updates: %v\n", err)
		os.Exit(1)
	}

	if latest == currentVersion {
		fmt.Printf("already up to date (%s)\n", currentVersion)
		return
	}

	if !isNewer(latest, currentVersion) {
		// versions differ but neither is parseable as semver — don't silently
		// claim "up to date" when we actually cannot compare them.
		_, latestOk := parseSemver(latest)
		_, currentOk := parseSemver(currentVersion)
		if !latestOk || !currentOk {
			fmt.Fprintf(os.Stderr, "bonsai: cannot compare versions %q and %q\n", latest, currentVersion)
			os.Exit(1)
		}
		fmt.Printf("already up to date (%s)\n", currentVersion)
		return
	}

	fmt.Printf("updating %s -> %s\n", currentVersion, latest)

	binaryName := buildBinaryName()
	url := fmt.Sprintf("https://github.com/%s/releases/download/%s/%s", repo, latest, binaryName)

	exe, err := os.Executable()
	if err != nil {
		fmt.Fprintf(os.Stderr, "bonsai: failed to find current binary: %v\n", err)
		os.Exit(1)
	}

	tmpPath := exe + ".tmp"
	if err := download(url, tmpPath); err != nil {
		fmt.Fprintf(os.Stderr, "bonsai: update failed: %v\n", err)
		os.Remove(tmpPath)
		os.Exit(1)
	}

	if err := verifyChecksum(tmpPath, latest, binaryName); err != nil {
		fmt.Fprintf(os.Stderr, "bonsai: verification failed: %v\n", err)
		os.Remove(tmpPath)
		os.Exit(1)
	}

	if err := replaceBinary(exe, tmpPath); err != nil {
		fmt.Fprintf(os.Stderr, "bonsai: failed to replace binary: %v\n", err)
		os.Remove(tmpPath)
		os.Exit(1)
	}

	fmt.Printf("updated to %s\n", latest)
}

// IsDev reports whether the version looks like a dev build.
func IsDev(version string) bool {
	return version == "dev" || strings.Contains(version, "-dirty")
}

func latestVersion() (string, error) {
	url := fmt.Sprintf("https://api.github.com/repos/%s/releases/latest", repo)
	resp, err := httpClient.Get(url)
	if err != nil {
		return "", fmt.Errorf("could not reach GitHub (check your internet connection): %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		return "", fmt.Errorf("GitHub API returned %d", resp.StatusCode)
	}

	var release ghRelease
	if err := json.NewDecoder(io.LimitReader(resp.Body, maxResponseBytes)).Decode(&release); err != nil {
		return "", fmt.Errorf("failed to parse GitHub response: %w", err)
	}
	if release.TagName == "" {
		return "", fmt.Errorf("empty tag_name in GitHub response")
	}
	return release.TagName, nil
}

func buildBinaryName() string {
	goos := runtime.GOOS
	goarch := runtime.GOARCH
	ext := ""
	if goos == "windows" {
		ext = ".exe"
	}
	return fmt.Sprintf("bonsai-%s-%s%s", goos, goarch, ext)
}

func download(url, destPath string) error {
	resp, err := httpClient.Get(url)
	if err != nil {
		return fmt.Errorf("download failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == 404 {
		return fmt.Errorf("release binary not found — this platform may not be supported yet")
	}
	if resp.StatusCode != 200 {
		return fmt.Errorf("download returned %d for %s", resp.StatusCode, url)
	}

	f, err := os.OpenFile(destPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o700)
	if err != nil {
		return fmt.Errorf("failed to create temp file: %w", err)
	}

	_, copyErr := io.Copy(f, resp.Body)
	closeErr := f.Close()
	if copyErr != nil {
		return fmt.Errorf("failed to write binary: %w", copyErr)
	}
	if closeErr != nil {
		return fmt.Errorf("failed to flush binary to disk: %w", closeErr)
	}

	info, err := os.Stat(destPath)
	if err != nil {
		return fmt.Errorf("failed to stat downloaded file: %w", err)
	}
	if info.Size() < 1024 {
		return fmt.Errorf("downloaded file too small (%d bytes)", info.Size())
	}
	return checkBinaryMagic(destPath)
}

func checkBinaryMagic(path string) error {
	f, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("failed to open binary for validation: %w", err)
	}
	defer f.Close()

	buf := make([]byte, 4)
	if _, err := io.ReadFull(f, buf); err != nil {
		return fmt.Errorf("binary too small to read magic bytes: %w", err)
	}

	switch runtime.GOOS {
	case "linux":
		if buf[0] != 0x7f || buf[1] != 'E' || buf[2] != 'L' || buf[3] != 'F' {
			return fmt.Errorf("downloaded file is not a valid ELF binary")
		}
	case "darwin":
		valid := (buf[0] == 0xca && buf[1] == 0xfe && buf[2] == 0xba && buf[3] == 0xbe) ||
			(buf[0] == 0xcf && buf[1] == 0xfa && buf[2] == 0xed && buf[3] == 0xfe) ||
			(buf[0] == 0xce && buf[1] == 0xfa && buf[2] == 0xed && buf[3] == 0xfe) ||
			(buf[0] == 0xfe && buf[1] == 0xed && buf[2] == 0xfa && buf[3] == 0xcf) ||
			(buf[0] == 0xfe && buf[1] == 0xed && buf[2] == 0xfa && buf[3] == 0xce)
		if !valid {
			return fmt.Errorf("downloaded file is not a valid Mach-O binary")
		}
	case "windows":
		if buf[0] != 'M' || buf[1] != 'Z' {
			return fmt.Errorf("downloaded file is not a valid PE binary")
		}
	}
	return nil
}

func verifyChecksum(binaryPath, version, binaryName string) error {
	checksums, err := fetchReleaseFile(version, "checksums.txt")
	if err != nil {
		return fmt.Errorf("failed to fetch checksums.txt: %w", err)
	}

	signature, err := fetchReleaseFile(version, "checksums.txt.sig")
	if err != nil {
		return fmt.Errorf("failed to fetch checksums.txt.sig: %w", err)
	}

	if err := verifySignature(checksums, signature); err != nil {
		return fmt.Errorf("invalid signature for checksums.txt: %w", err)
	}

	expected, err := parseChecksum(string(checksums), binaryName)
	if err != nil {
		return err
	}

	actual, err := hashFile(binaryPath)
	if err != nil {
		return fmt.Errorf("failed to hash downloaded binary: %w", err)
	}

	if actual != expected {
		return fmt.Errorf("SHA256 mismatch: expected %s, got %s", expected, actual)
	}
	return nil
}

func verifySignature(message, signature []byte) error {
	return verifySignatureWithKey(publicKey, message, signature)
}

func verifySignatureWithKey(keyHex string, message, signature []byte) error {
	pub, err := hex.DecodeString(keyHex)
	if err != nil || len(pub) != ed25519.PublicKeySize {
		return errors.New("public key not configured — run 'make keygen'")
	}

	sig, err := hex.DecodeString(strings.TrimSpace(string(signature)))
	if err != nil {
		return fmt.Errorf("invalid signature format: %w", err)
	}

	if !ed25519.Verify(pub, message, sig) {
		return errors.New("Ed25519 signature verification failed")
	}
	return nil
}

func fetchReleaseFile(version, filename string) ([]byte, error) {
	url := fmt.Sprintf("https://github.com/%s/releases/download/%s/%s", repo, version, filename)
	resp, err := httpClient.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode == 404 {
		return nil, fmt.Errorf("%s not found in release %s", filename, version)
	}
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("%s returned %d", filename, resp.StatusCode)
	}
	return io.ReadAll(io.LimitReader(resp.Body, maxResponseBytes))
}

func parseChecksum(checksums, binaryName string) (string, error) {
	for _, line := range strings.Split(checksums, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		i := strings.IndexByte(line, ' ')
		if i == -1 {
			continue
		}
		hash := line[:i]
		rest := strings.TrimLeft(line[i+1:], " ")
		name := strings.TrimPrefix(rest, "*")
		if name == binaryName {
			return hash, nil
		}
	}
	return "", fmt.Errorf("no checksum found for %s", binaryName)
}

func replaceBinary(destPath, srcPath string) error {
	if runtime.GOOS == "windows" {
		// Windows locks running executables against in-place replacement but
		// allows renaming them away. Two-step: move current → .old (safe while
		// running), then move .tmp → current (now uncontested).
		// CleanupStaleUpdate removes the .old file on the next startup.
		oldPath := destPath + ".old"
		os.Remove(oldPath) // remove any leftover from a previous attempt
		if err := os.Rename(destPath, oldPath); err != nil {
			return fmt.Errorf("could not move current binary aside: %w", err)
		}
		if err := os.Rename(srcPath, destPath); err != nil {
			// best-effort rollback
			os.Rename(oldPath, destPath)
			return fmt.Errorf("could not replace binary: %w", err)
		}
		return nil
	}
	// Linux/macOS: os.Rename atomically replaces the path entry.
	// Running processes keep their existing file descriptor unaffected.
	return os.Rename(srcPath, destPath)
}

// CleanupStaleUpdate removes leftover temp files from a previous update attempt.
// Call this at startup before doing anything else.
func CleanupStaleUpdate() {
	exe, err := os.Executable()
	if err != nil {
		return
	}
	os.Remove(exe + ".tmp") // aborted download
	os.Remove(exe + ".old") // legacy: left by pre-v0.66.1 updates on Windows
}

func hashFile(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

func isNewer(a, b string) bool {
	pa, ok1 := parseSemver(a)
	pb, ok2 := parseSemver(b)
	if !ok1 || !ok2 {
		return false
	}
	if pa[0] != pb[0] {
		return pa[0] > pb[0]
	}
	if pa[1] != pb[1] {
		return pa[1] > pb[1]
	}
	return pa[2] > pb[2]
}

func parseSemver(v string) ([3]int, bool) {
	v = strings.TrimPrefix(v, "v")
	parts := strings.SplitN(v, ".", 3)
	if len(parts) != 3 {
		return [3]int{}, false
	}
	var nums [3]int
	for i, p := range parts {
		n := 0
		for _, c := range p {
			if c < '0' || c > '9' {
				return [3]int{}, false
			}
			n = n*10 + int(c-'0')
		}
		nums[i] = n
	}
	return nums, true
}
